SysAdmin Base v2.0
SDIsl/valentin-addons pull request #14
Opened 2021-02-22 22:09 UTC by valentincastravete

- Creados modelos **workspace.workspace** y **workspace.item** y vistas correspondientes.
- Empleado en grupo **group_workspace**, tiene pestaña con acceso a sus espacios de trabajo para mover los artículos entre estos.
- Empleado en grupo **group_sysadmin**, tiene permisos para ver todos los menús, crear, modificar y eliminar cualquier espacio de trabajo, artículo y relaciones entre producto y artículo y empleado y espacio de trabajo.

2021-02-24 11:18 UTC, valentincastravete commented
No revisar todavía, haré otro commit cambiando unas cosas.

2021-03-03 16:43 UTC, valentincastravete commented
@oscars8a @JorgeQuinteros Ya están los commit con todo lo hablado, implementado.

PD: Sergio Lop me ha comentado que no realizara el empleado responsable con el sequence y lo he quitado, pero de todas formas he aprendido como utilizar un sequence y un widget handle drag and drop.

2021-03-09 12:27 UTC, oscars8a requested changes
Divide las clases workspace en distintos ficheros tanto en .py como en .xml y mirame lo de los grupos. Lo demás guay.

2021-03-09 12:27 UTC, oscars8a commented on sysadmin_base/.vscode/launch.json
> +    // Use IntelliSense para saber los atributos posibles.
```suggestion
```

2021-03-09 12:27 UTC, oscars8a commented on sysadmin_base/.vscode/launch.json
> +    // Mantenga el puntero para ver las descripciones de los existentes atributos.
```suggestion
```

2021-03-09 12:27 UTC, oscars8a commented on sysadmin_base/.vscode/launch.json
> +    // Para más información, visite: https://go.microsoft.com/fwlink/?linkid=830387
```suggestion
```

2021-03-09 12:27 UTC, oscars8a commented on sysadmin_base/models/workspace.py
> +    _name = 'workspace.item'
Saca el workspace.item en otro fichero, nosotros aplicamos el 1 fichero 1 clase

2021-03-09 12:27 UTC, oscars8a commented on sysadmin_base/security/sysadmin_security.xml
> +            <field name="implied_ids" eval="[(4, ref('base.group_user'))]"/>
Esto no hace que todos los que están en el grupo group_user pasen a formar parte del grupo Sysadmin?

2021-03-09 12:27 UTC, oscars8a commented on sysadmin_base/security/sysadmin_security.xml
> +            <field name="implied_ids" eval="[(4, ref('base.group_user'))]"/>
En este caso sería el grupo de empleados no el de group_user

2021-03-09 12:27 UTC, oscars8a commented on sysadmin_base/views/workspace_views.xml
> +        <field name="name">workspace.item.view.search</field>
Lo mismo, divide las clases "workspace" en distintos ficheros xml 1 clase 1 fichero .xml

2021-03-09 12:52 UTC, valentincastravete commented on sysadmin_base/security/sysadmin_security.xml
> +            <field name="implied_ids" eval="[(4, ref('base.group_user'))]"/>
Con lo que he hecho, he entendido que si metes a un usuario al grupo **SysAdmin**, también lo mete en el grupo **group_user (Usuario Interno)**, no al revés.

Esto lo he hecho por que, si metes a un usuario en el grupo **SysAdmin**, para poder acceder al backend, tendrá que ser **Usuario Interno** también, y para ahorrar tiempo en añadir usuarios a ese grupo también, le he puesto ese **implied_ids** y lo mete automáticamente.

Corrígeme si me equivoco

2021-03-09 12:55 UTC, valentincastravete commented on sysadmin_base/security/sysadmin_security.xml
> +            <field name="implied_ids" eval="[(4, ref('base.group_user'))]"/>
Esto viene a ser lo mismo, los **SysAdmin / Employee** también pasan a ser **Usuarios Internos** para poder acceder al backend.

¿Estaría bien hacer que todos los empleados se conviertan en SysAdmin / Employee? Ya que esta funcionalidad de momento no se usará, de momento.

2021-03-09 13:02 UTC, oscars8a commented on sysadmin_base/security/sysadmin_security.xml
> +            <field name="implied_ids" eval="[(4, ref('base.group_user'))]"/>
Un usuario con acceso al backend siempre pertenece a Usuarios Interno, es redundante, lo puedes quitar.

2021-03-09 13:04 UTC, oscars8a commented on sysadmin_base/security/sysadmin_security.xml
> +            <field name="implied_ids" eval="[(4, ref('base.group_user'))]"/>
Todo usuario que pertenece a empleados también pertenece a Usuarios Internos. en el Sys employee pondria a los hr.employee en todo caso.

2021-03-15 14:49 UTC, oscars8a requested changes
Tengo dudas con respecto al __pycache__ en el gitignore

2021-03-15 14:49 UTC, oscars8a commented on .gitignore
> +.~*
por que modificas ésto? ahora se subirá el __pycache__ no?

2021-03-15 14:55 UTC, oscars8a approved these changes
Todo correcto.

2021-03-17 08:57 UTC, merged