Corregir permisos, dependencias y nombres
SDIsl/valentin-addons pull request #15
Opened 2021-03-17 10:17 UTC by valentincastravete

Correción del conflicto de permisos, dependencia a product en vez de stock y cambio de nombres y traducciones

2021-03-17 10:20 UTC, oscars8a approved these changes
.

2021-03-17 12:34 UTC, valentincastravete commented
Añadida vista Calendario a módulo Partes de horas

2021-03-18 09:22 UTC, oscars8a approved these changes
.

2021-03-23 11:07 UTC, oscars8a requested changes
Ese if te puede salir mejor.

2021-03-23 11:07 UTC, oscars8a commented on sysadmin_base/models/workspace_item.py
> +        if self.amount < 0:
haces la misma comprobación dos veces (self.amount < 0), reformula el if, seguro que te sale mejor. Creo que python puede comparar False > 0 ya que False lo equivale a 0 pero tengo mis dudas.

2021-03-23 11:31 UTC, oscars8a approved these changes
.

2021-03-24 10:09 UTC, merged