Mejoras y Necesidades
SDIsl/valentin-addons pull request #16
Opened 2021-03-24 11:06 UTC by valentincastravete

2021-03-24 12:21 UTC, oscars8a requested changes
Hacer una regla constraint que ralentiza la BD solo para comprobar que un campo entero es menor que 0, cuando lo normal es no lo sea es matar moscas a cañonazos, prueba esta opción de html... https://www.w3schools.com/tags/att_input_min.asp

2021-04-11 12:49 UTC, JorgeQuinteros approved these changes

2021-04-13 16:30 UTC, JorgeQuinteros approved these changes

2021-04-13 16:30 UTC, JorgeQuinteros commented on sysadmin_base/models/hr_employee.py
> +            'name': 'Edit Internal Tools',
_('Edit Internal Tools'),

2021-04-13 16:30 UTC, valentincastravete commented on sysadmin_base/models/hr_employee.py
> +            'name': 'Edit Internal Tools',
Ya está ;)

2021-04-13 16:34 UTC, oscars8a approved these changes
Todo guay

2021-04-13 16:34 UTC, merged