Archivos flake8.yml y prueba.py
SDIsl/valentin-addons pull request #5
Opened 2021-01-27 17:02 UTC by valentincastravete

He creado el fichero **flake8.yml** con la función de comprobar en todo el repositorio, si los archivos con extesión **.py** cumples con las reglas de **Flake8**.
Para ello he creado el archivo **prueba.py**, añadiendo un comentario con más de 79 caracteres.
Cuando se ejecuta, si encuentra algún error en algún fichero al hacer un **push** o un **pull request**, crea un comentario en esa línea indicando el error que se ha cometido.

2021-01-28 10:44 UTC, JorgeQuinteros approved these changes

2021-01-28 15:41 UTC, oscars8a requested changes
Puedes enseñarnos el comentario en el que te dice el fallo? Graciass

2021-01-28 17:47 UTC, valentincastravete commented
El comentario y documentario están en el documento de drive de Imanol, que no te lo he contado, a Jorge sí. He nombrado su parte y he creado la mía de documentación.

2021-01-29 10:14 UTC, oscars8a commented
> El comentario y documentación están en el documento de drive de Imanol, que no te lo he contado, a Jorge sí. He nombrado su parte y he creado la mía de documentación.

Perfecto Valentín. Creo que tienes que marcar como resuelta mi petición de cambios para poder mergear tu PR. Un saludo.

2021-01-29 10:14 UTC, oscars8a approved these changes
Perfecto. No tienes que hacer nada más.

2021-01-29 10:14 UTC, merged