Modelos Producto y Empleado y sus Vistas v1
SDIsl/valentin-addons pull request #6
Opened 2021-02-04 16:44 UTC by valentincastravete

### Usos implementados

**Stock**

- Cualquier producto tiene la opción de ser un equipo interno, dando la posibilidad de una nueva página de Información Técnica del equipo.
- Implementa una opción que le permite completar campos de hardware de productos asociados con una categoría que tiene habilitada la opción "Mostrar propiedades de hardware".
- También puede filtrar por "equipos internos".

**Empleados**

- Los empleados tienen 2 campos que indican si ese empleado tiene acceso a Dialoga y si ese empleado está en prácticas
- En la vista de árbol, puede ver si los empleados "Tiene acceso a Dialoga".
- Permite filtrar por "Tiene acceso a Dialoga" y agrupar por "En prácticas".

2021-02-08 15:22 UTC, oscars8a requested changes
Bastante bien, revisa los puntos a cambiar.

2021-02-08 15:22 UTC, oscars8a commented on prueba.py
> +#   Comentario con más de 80 caracteres para probar que flake8 hace su función
Elimina ya este fichero.

2021-02-08 15:22 UTC, oscars8a commented on sysadmin_base/__manifest__.py
> +        'views/product_category_views.xml',
Orden alfabético.

2021-02-08 15:22 UTC, oscars8a commented on sysadmin_base/models/__init__.py
> +from . import product_template
orden alfabético.

2021-02-08 15:22 UTC, oscars8a commented on sysadmin_base/views/product_category_views.xml
> +</odoo>
añadir linea al final del fichero.

2021-02-09 10:38 UTC, JorgeQuinteros requested changes

2021-02-09 10:38 UTC, JorgeQuinteros commented on sysadmin_base/models/hr_employee.py
> +    has_dialoga_access = fields.Boolean(string='Has Dialoga access')
Los campos los escribimos de la siguiente manera:`
```suggestion
    has_dialoga_access = fields.Boolean(
        string='Has Dialoga access',
    )
```
Esto hace más fácil la lectura de código, y si a futuro añades un "help", GIT sólo pintará una línea de más porque se habrá añadido un cambio, por lo que también será más fácil de detectar qué tipo de cambio se ha realizado

2021-02-09 10:38 UTC, JorgeQuinteros commented on sysadmin_base/models/hr_employee.py
> +    is_trainee = fields.Boolean(string='Is trainee')
Lo mismo que antes, revisa todo y ponlo como te he sugerido en `has_dialoga_access.`

2021-02-09 10:38 UTC, JorgeQuinteros commented on sysadmin_base/views/hr_employee_views.xml
> +            <xpath expr="//field[@name='work_phone']" position="after">
Esto no está mal, pero también puedes hacer esto, es más sencillo:
``<field name="work_phone" position="after">
      <field name="has_dialoga_access"/>
</field>``

2021-02-09 10:56 UTC, valentincastravete commented on sysadmin_base/views/product_template_views.xml
> +            </div>
¿Hay alguna forma de mejorar esto?

2021-02-09 12:09 UTC, JorgeQuinteros commented on sysadmin_base/views/product_template_views.xml
> +            </div>
Sí, se puede hacer mediante xpath:
Haz referencia al field name="sale_ok" y luego utiliza "/.." para hacer referencia al elemento anterior, que sería el div.
Por ejemplo:
```
<xpath expr="//loquesea/field[@name='sale_ok']/.." position="after">
         <div id="internal_equipment_div">
                    <field name="internal_equipment"/>
                    <label for="internal_equipment"/>
                </div>
</xpath>
```

2021-02-09 14:45 UTC, valentincastravete commented on sysadmin_base/views/product_template_views.xml
> +            </div>
¿Lo que has dicho lo dejaría así?:

```
<div name="options" position="replace">
                <div>
                    <field name="sale_ok"/>
                    <label for="sale_ok"/>
                </div>
                <div>
                    <field name="internal_equipment"/>
                    <label for="internal_equipment"/>
                </div>
```

¿O así?:

```
<div name="options" position="replace">
                <div>
                    <field name="sale_ok"/>
                    <div>
                        <field name="internal_equipment"/>
                        <label for="internal_equipment"/>
                    </div>
                    <label for="sale_ok"/>
                </div>
                
```

2021-02-09 16:40 UTC, JorgeQuinteros commented on sysadmin_base/views/product_template_views.xml
> +            </div>
Pruebalo y me dices

2021-02-10 09:13 UTC, JorgeQuinteros requested changes

2021-02-10 09:13 UTC, JorgeQuinteros commented on sysadmin_base/models/product_template.py
> +
Esta línea fuera

2021-02-10 09:13 UTC, JorgeQuinteros commented on sysadmin_base/models/product_template.py
> +
Línea en blanco fuera

2021-02-10 09:13 UTC, JorgeQuinteros commented on sysadmin_base/models/product_template.py
> +
Ídem

2021-02-10 10:30 UTC, JorgeQuinteros approved these changes
Approve!

2021-02-10 12:44 UTC, oscars8a approved these changes
Perfe

2021-02-10 14:56 UTC, merged